### ISSUE TITLE
Allow soundcloud and spotify links to be played

### ISSUE THREAD

**Issue by bullpoo1234** [ZeNyfh/gigavibe#48]

**Comment by ZeNyfh** [comment]
soundcloud not working is a bug with lavaplayer (i will look into re-building disky with a fix)
spotify support would be hellish to add as i would need to hack together some java code (planned feature, not yet implemented)

**Comment by ZeNyfh** [comment]
soundcloud is now working, + this is a duplicate
spotify support will be thought through again as i learned that discord bots get the spotify audio from youtube anyways.
