### ISSUE TITLE
rate limit for play command has false positives (still)

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe#57]
it literally clears the rate limiter after anything is met in the play command, it should be fine but apparently not, ill look into it later.

**Comment by ZeNyfh** [comment]
was triggered by trying to play a spotify link (invalid link) and then a youtube link

**Comment by ZeNyfh** [comment]
fixed, will be pushed in the next update (and closed)

**Comment by 9382** [comment]
So was it pushed and fixed? Make sure to be closing stuff you've done

**Comment by ZeNyfh** [comment]
pushed and fixed, forgot to close.
