### ISSUE TITLE
make it so the bot doesnt send a double message on first play

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe#63]
basically fix this
![image](https://user-images.githubusercontent.com/66276905/155909179-5af9e046-63fe-4b45-a793-1d4cf58efefa.png)

theory: disallow it from sending the 2nd embed if it returns true (cancels the send embed event), eg (some example code)

`if track is first in queue:
    set {%id of event-guild%.embedstop} to true
else:
    clear {%id of event-guild%.embedstop}`

`if {%id of event-guild%.embedstop} is true:
    exit
else:
    %embed code here%`

**Comment by 9382** [comment]
Possibly simple solution: if the queue size after adding the new play song is 1 (aka its the first one added after being empty), then simply dont post the embed from the play command (line 249)? Stopping the one in the track start might possibly be harder (line 383)

**Comment by ZeNyfh** [comment]
> Possibly simple solution: if the queue size after adding the new play song is 1 (aka its the first one added after being empty), then simply dont post the embed from the play command (line 249)? Stopping the one in the track start might possibly be harder (line 383)

thanks, took inspiration from this:

![image](https://user-images.githubusercontent.com/66276905/158286239-0660745d-9ed4-4309-9371-893caff920fd.png)
